### PR TITLE
var->const and internal trait.zig to compile on latest zig

### PR DESCRIPTION
**Pull request by dvmason**
Zig version 0.12.0-dev.1808+69195d0cd

Really want this to work on macos

### CODE REVIEW

**Comment by dvmason** [comment]
accidentally checked in version that was WIP.... cleaned up now.

**Comment by AdjectiveAllison** [comment]
+1 capy is unusable on master zig without this change.

**Comment by AdjectiveAllison** [comment]
@dvmason It looks like there is still more work to be done to get this working on zig master. I submitted a pull request to your fork with a decent amount of additional changes and extra information on what else is left.

Here is the link:
https://github.com/dvmason/capy/pull/1

After digging in more, I really like the way you are making it compatible with both 0.11.0 and master branch by creating trait.zig and using std.meta.trait if available, otherwise using the local functions.

**Comment by dvmason** [comment]
All compiles cleanly in 0.12.0-dev.1830+779b8e259 now.
Almost compiles in 0.11.0 but still has an error I can't figure out

**Comment by dvmason** [comment]
Helps if I do it right! needed @hasDecl instead of @hasField

**Comment by AdjectiveAllison** [comment]
https://github.com/dvmason/capy/pull/2

Sent up another PR David's way with some more fixes for my local environment. Here is my current status on master:
`Build Summary: 38/49 steps succeeded; 5 failed`

One thing that I'm noticing though as I get closer to successful compilation is that I'm starting to hit build errors with the vendor repositories. Specifically `vendor/zigimg` is quite noisy. It looks like [zigimg](https://github.com/zigimg/zigimg) is keeping up to date with master, and the errors I get would be easily resolved with pulling the latest from source. However, it looks like the zigimg code isn't setup for backwards compatibility with 0.11.0, which all of a sudden means @dvmason and I's work to get capy compatibility working in both directions extends into another repository, and I don't know if that is sustainable. 

@zenith391, Do you have an opinion on how you'd prefer to handle zig language version compatibility within capy?

**Comment by zenith391** [comment]
I think I'll just restart keeping up with Zig master

**Comment by zenith391** [comment]
I'll merge the PR as is and fix the last few errors

**Comment by dvmason** [comment]
Great, thanks!

**Pull request merged**
