### PR TITLE
macos: implemented create, add, remove, move, resize in Container

### PR DESCRIPTION
**Pull request by geon**
Building the 300-buttons example now works on macos.

The layout is still all wrong, but at least the coordinate system in Container is Y-axis pointing down.

### CODE REVIEW

**Comment by zenith391** [comment]
Thanks for the pull request, but why was creating `FlippedNSView` required? I think the flipping could happen programatically in the `Container.move` function. For instance:
```zig
        const selfFrame = self.peer.getProperty(AppKit.NSRect, "frame");
        const peerFrame = peer.getProperty(AppKit.NSRect, "frame");

        peer.setProperty("frame", AppKit.NSRect.make(
            @floatFromInt(x),
            @floatFromInt(selfFrame.size.height) - @floatFromInt(y),
            peerFrame.size.width,
            peerFrame.size.height,
        ));
```

**Comment by geon** [comment]
Sure, I just felt having the coordinate systems match would be easier.

But perhaps it’s better to follow the NSView convention and convert between the coordinate spaces manually.

I think it would be a good idea to have a function for that though. 

Want me to change it?

**Comment by geon** [comment]
Since the height of the frames are taken into account, I don't think it will work at all until the window resize event is handled.

And I think it should be

```objc
        peer.setProperty("frame", AppKit.NSRect.make(
            @floatFromInt(x),
            selfFrame.size.height - peerFrame.size.height - @as(f64, @floatFromInt(y)),
            peerFrame.size.width,
            peerFrame.size.height,
        ));

```

**Comment by zenith391** [comment]
Oh ok, I'll merge the pull request for now and later see what to do once window resize events are being handled.

**Pull request merged**
